plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.116'
    id "me.modmuss50.mod-publish-plugin" version "0.8.3"
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)


base {
    archivesName = mod_id
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}


repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.shadowsoffire.dev/releases")
        content {
            includeGroup("dev.shadowsoffire")
            includeGroup("snownee.jade")
        }
    }
	maven { url = 'https://maven.cafeteria.dev'
		content {
			includeGroup 'net.adriantodt.fabricmc'
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ftb.dev/releases"
			}
		}
		filter {
			includeGroup"dev.latvian.mods"
			includeGroup"dev.ftb.mods"
		}
	}
	maven { url = "https://maven.nucleoid.xyz/" }
	maven { url = 'https://maven.blamejared.com' }
	maven { url = "https://maven.willbl.dev/releases" }
	maven { url = "https://maven.parchmentmc.org" }
	maven { url = "https://maven.terraformersmc.com/" }
	maven { url = 'https://maven.ladysnake.org/releases' }
	maven { url = 'https://maven.ladysnake.org/snapshots' }
	maven { url = "https://maven.shedaniel.me" }
	maven { url = "https://maven.bai.lol" }
	maven { url = 'https://maven.kosmx.dev/' }
	maven { url = "https://nexus.resourcefulbees.com/repository/maven-public/" }
	maven { url = "https://jm.gserv.me/repository/maven-public/" }
	maven { url = "https://masa.dy.fi/maven" }
	maven { url = "https://maven.quiltmc.org/repository/release" }
	maven { url = "https://maven.uuid.gg/releases" }
    maven {
        name = "Iron's Maven - Release"
        url = "https://code.redspace.io/releases"
    }
    maven {
        name = "Iron's Maven - Snapshots"
        url = "https://code.redspace.io/snapshots"
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup("software.bernie.geckolib")
        }
    }
    maven { url "https://maven.puffish.net" }
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
}


// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {

    // Origins
    implementation "curse.maven:origins-neoforge-1375372:7216492"

    // Dev Env
    localRuntime("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    implementation("snownee.jade:Jade-NeoForge:${minecraft_version}-${jade_version}")

    // Optional Compats:
    implementation("dev.shadowsoffire:Placebo:${minecraft_version}-${placebo}")
    implementation("dev.shadowsoffire:Apotheosis:${minecraft_version}-${apotheosis}")
    implementation("dev.shadowsoffire:ApothicAttributes:${minecraft_version}-${apothic_attributes}")
    implementation("dev.shadowsoffire:ApothicSpawners:${minecraft_version}-${apothic_spawners}")
    implementation("dev.shadowsoffire:ApothicEnchanting:${minecraft_version}-${apothic_enchanting}")

    // Puffish
    implementation ("net.puffish:skillsmod:${puffish_skills}:neoforge")
    localRuntime "curse.maven:default-skill-trees-1074229:5852412"
    localRuntime "curse.maven:puffish-attributes-991341:7183595"

    // just to fix the dev env crash
    localRuntime "curse.maven:patchouli-306770:6842247"

    // Iron's
    implementation ("io.redspace:irons_spellbooks:${irons_version}")
    runtimeOnly ("software.bernie.geckolib:geckolib-neoforge-${geckolib_version}")
    compileOnly ("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
    runtimeOnly ("top.theillusivec4.curios:curios-neoforge:${curios_version}")
    runtimeOnly("dev.kosmx.player-anim:player-animation-lib-forge:${player_animator}")


    // Mixin
	implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixin_extras_version}"))
	implementation(annotationProcessor("net.fabricmc:sponge-mixin:0.13.3+mixin.0.8.5"))

	// Icarus
    implementation ("maven.modrinth:icarus:${project.icarus_version}")
	localRuntime ("com.teamresourceful.resourcefulconfig:resourcefulconfig-neoforge-1.21:${project.resourceful_version}")
    localRuntime ("mysticdrew:common-networking-neoforge:${project.cmnw_version}")
    localRuntime "dev.upcraft.sparkweave:Sparkweave-NeoForge:${project.sparkweave_version}"

	// FTB
    implementation("dev.ftb.mods:ftb-library-neoforge:${project.ftb_library_version}")
    implementation("dev.ftb.mods:ftb-teams-neoforge:${project.ftb_teams_version}")

	// Ice and Fire: CE
    implementation "curse.maven:iceandfire-ce-1040076:7210417"
    implementation "curse.maven:uranus-1010827:6979353"
    implementation "curse.maven:jupiter-1072905:6843052"
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
    changelog = new File("$project.rootDir/CHANGELOG.md").getText('UTF-8')
    version = "${mod_version}+${minecraft_version}"
    type = BETA
    displayName = "${mod_version}+${minecraft_version}"

    curseforge {
        projectId = "${curseforge_project}"
        accessToken = System.getenv("CF_TOKEN")

        minecraftVersions.add(minecraft_version)
        javaVersions.add(JavaVersion.VERSION_21)

        clientRequired = true
        serverRequired = true

        // Dependencies
        requires "origins-neoforge"
    }

    // TODO: Modrinth Publish
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}