# Project
version=6.6.0
group=dev.muon
org.gradle.jvmargs=-Xmx3G -Djavax.net.preferIPv4Stack=true -XX:MaxMetaspaceSize=1G
org.gradle.daemon=false
java_version=17

# Mod options
mod_name=Medieval Origins Revival
description=Origins inspired by mythology, fantasy, and the medieval era.
mod_author=MuonR
mod_id=medievalorigins
license=GNU GPLv3.0
forge_loader_version_range=[47,)
credits=


# Common
minecraft_version=1.20.1
parchment_version=2023.09.03
parchment_minecraft=1.20.1
mixin_extras_version=0.5.0
forge_version=47.4.10
forge_ats_enabled=false
fabric_loader_version=0.17.3
fabric_version=0.92.6+1.20.1
minecraft_version_range=[1.20.1)

# calio_version=v1.11.2
# apoli_version=v2.9.2
# origins_version=v1.10.2


# Publishing
forge_mod_loaders=Forge
forge_game_versions=1.20.1

# Misc Required
cpa_version = 1.0.0
rea_version=2.4.0
aea_version=1.7.4+1.20.0
pehkui_version=3.8.2
cca_version=5.2.2
pal_version=1.8.0
trinkets_version=3.7.0
geckolib_version=1.20.1:4.8.2
caelus_version=3.1.0

rei_version=12.0.684
jei_version=15.2.0.27
cloth_config_version=11.1.118
jade_id=6291330

ars_version=4.11.0.192
irons_version=1.20.1-3.4.0.11
curios_version=5.14.1+1.20.1

# Deprecated for removal
projectile_damage=3.2.2+1.20.1

# Icarus + Dependencies
icarus_version=2.9.0
cmnw_version=1.0.3-1.20.1
resourceful_version=2.1.2

# RPG Series
bettercombat_version=1.8.5+1.20.1
player_animator_version=1.0.2-rc1+1.20
ranged_weapon_api_version=1.1.2+1.20.1
spell_power_version=0.11.0+1.20.1
spell_engine_version=0.15.6+1.20.1
runes_version=0.9.13+1.20.1
wizards_version=1.2.2+1.20.1
paladins_version=1.2.6+1.20.1
archers_version=1.2.4+1.20.1
jewelry_version=1.3.4+1.20.1
structure_pool_api_version=1.0+1.20.1
tiny_config_version=2.3.2
azure_lib_version=1.0.2
player_anim_version=1.0.2+1.19.4

# Rpg difficulty compat testing
rpg_version=1.3.13+1.20.1

ftb_teams_version=2001.3.1
ftb_library_version=2001.2.10