# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.206
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=medievalorigins
mod_name=Medieval Origins Revival
mod_license=MIT+CC-BY-4.0
mod_version=7.0.4-alpha-1
mod_group_id=dev.muon.medievalorigins
mod_authors=MuonR
mod_description=Origins inspired by mythology, fantasy, and the medieval era.

# Mixin
mixin_extras_version=0.4.1

# Icarus
icarus_version=4.5.0+NeoForge
cmnw_version=1.0.16-1.21.1
resourceful_version=3.0.8
trinkets_version=3.10.0
sparkweave_version=0.510.0

# Spell Engine / RPG
spell_engine_version=1.6.12+1.21.1
spell_power_version=1.3.0+1.21.1
player_anim_version=2.0.0+1.21.1
cloth_config_version=15.0.140
tiny_config_version=2.3.2

## FTB
ftb_teams_version=2101.1.2
ftb_library_version=2101.1.7

# Publishing
curseforge_project=897171

# Dev Env
jei_version=19.21.0.247
jade_version=15.1.6

# Integrations
apotheosis=8.4.0
apothic_enchanting=1.5.0
apothic_spawners=1.3.0
placebo=9.9.1
apothic_attributes=2.8.0

geckolib_version=1.21.1:4.7.5.1
irons_version=1.21.1-3.11.0
curios_version=9.5.1+1.21.1

player_animator=2.0.1+1.21.1
cloth_config=15.0.140

puffish_skills=0.16.8+1.21