plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    flatDir { dir "${rootProject.rootDir}/libs/forge/" }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { url 'https://maven.kosmx.dev/' }
    maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'}
    maven { url "https://code.redspace.io/releases" }
    maven { url "https://code.redspace.io/snapshots" }
    maven { url "https://maven.blamejared.com" }
    maven { url "https://maven.ladysnake.org/releases" }

    maven { url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven" }
    }
    maven { url "https://maven.shedaniel.me" }

    maven {
        url = "https://jm.gserv.me/repository/maven-public/"
    }
    maven { url = 'https://maven.theillusivec4.top' }
    maven { url = "https://modmaven.dev"
        content {
            excludeGroup "com.teamresourceful.resourcefulconfig"}
    }
    maven { url = "https://nexus.resourcefulbees.com/repository/maven-public/" }
    maven {
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup("dev.latvian.mods")
            includeGroup("dev.ftb.mods")
        }
    }
    mavenCentral()
    mavenLocal()
    maven {
        name = "JitPack"
        url = 'https://jitpack.io'
        content {
            excludeGroup "io.github.edwinmindcraft"
        }
    }

}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    // Origins (from local libs/forge directory)
    // This is a modified version of the Origins jar, with Reach Entity Attributes removed manually, since gradle was failing to exclude it
    // modImplementation ("io.github:Origins-1.10.2+mc.1.20.x_mapped_srg_1.20.1")
    // Remapped versions of Origins' bundled jars
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x_mapped_srg_1.20.1")
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$calio-1.11.2+mc.1.20.x_mapped_srg_1.20.1")
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$cardinal-components-base-5.2.1_mapped_srg_1.20.1")
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$cardinal-components-entity-5.2.1_mapped_srg_1.20.1")
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$PlayerAbilityLib-1.8.0_mapped_srg_1.20.1")
    modImplementation ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$AdditionalEntityAttributes-1.7.4+1.20.0_mapped_srg_1.20.1")

    // Mixin
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    jarJar(implementation("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}")) {
        version {
        strictly '[0.5.0, 1.0)'
        prefer '0.5.0'
        }
    }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // Connector
    modImplementation ("curse.maven:sinytra-connector-890127:5761411")
    // implementation ("curse.maven:connector-extras-913445:5490637")
    modImplementation ("curse.maven:forgified-fabric-api-889079:6885853")

    // Icarus
    modImplementation ("maven.modrinth:icarus:${project.icarus_version}+NeoForge")
    modRuntimeOnly ("com.teamresourceful.resourcefulconfig:resourcefulconfig-forge-1.20.1:${project.resourceful_version}")
    modRuntimeOnly ("mysticdrew:common-networking-forge:${project.cmnw_version}")
    modCompileOnly(("top.theillusivec4.curios:curios-forge:${curios_version}:api"))
    modRuntimeOnly(("top.theillusivec4.curios:curios-forge:${curios_version}"))

    // Iron's Spells n Spellbooks
    modImplementation ("io.redspace.ironsspellbooks:irons_spellbooks:${irons_version}")
    modRuntimeOnly ("software.bernie.geckolib:geckolib-forge-${geckolib_version}")
    modRuntimeOnly ("dev.kosmx.player-anim:player-animation-lib-forge:${player_animator_version}")
    modRuntimeOnly ("top.theillusivec4.caelus:caelus-forge:${caelus_version}+1.20")

    // Ice and Fire
    modImplementation ("curse.maven:ice-and-fire-dragons-264231:5633453")
    modImplementation ("curse.maven:citadel-331936:5633260")

    // FTB
    modImplementation ("dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}")
    modRuntimeOnly ("dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}")
    modRuntimeOnly ("curse.maven:architectury-api-419699:5137938")
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}