plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id 'dev.mixinmcp.decompile'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    flatDir { dir "${rootProject.rootDir}/libs/forge/" }
    // flatDir { dir "${rootProject.rootDir}/libs/" }
    maven {
        name = 'Sponge / Mixin'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
    maven {
        name = "JitPack"
        url = 'https://jitpack.io'
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup("dev.latvian.mods")
            includeGroup("dev.ftb.mods")
        }
    }
    // Architectury, for FTB - for some reason Loom needs repos for recursive dependencies even if the root dependency is compileOnly?
    maven { url "https://maven.shedaniel.me" }
    // Origins
    maven { url = 'https://maven.ladysnake.org/releases' }
    // UpCraft, for Icarus
    maven { url "https://maven.uuid.gg/releases" }
    // Common Network API used by Icarus - for some reason Loom needs repos for recursive dependencies even if the root dependency is compileOnly?
    maven {url = "https://jm.gserv.me/repository/maven-public/"}
    // Resourceful Config, same as above
    maven {url = "https://maven.teamresourceful.com/repository/maven-public/"}
    mavenCentral()
    mavenLocal()
}

dependencies {
    // Origins
    modCompileOnly ("io.github:Origins-1.10.2+mc.1.20.x_mapped_srg_1.20.1")
    modCompileOnly ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x_mapped_srg_1.20.1")
    modCompileOnly ("io.github:Origins-1.10.2+mc.1.20.x\$apoli-2.9.2+mc.1.20.x\$calio-1.11.2+mc.1.20.x_mapped_srg_1.20.1")

    // If using MDG and these need to be directly used, they will need to be remapped (but we don't reference them ourselves)
    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}") {exclude(group: "net.fabricmc.fabric-api") transitive false}
    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}") {exclude(group: "net.fabricmc.fabric-api") transitive false}

    modCompileOnly("dev.ftb.mods:ftb-teams:${project.ftb_teams_version}")

    modCompileOnly("dev.cammiescorner.icarus:Icarus-Common:${project.icarus_version}")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.4'

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}
configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}