plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

archivesBaseName = "${mod_name}"
version = "${rootProject.version}+${minecraft_version}-common"

loom {
    if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.mixins.refmap.json")
    }
}


repositories {
    flatDir { dir "${rootProject.rootDir}/libs/" }
    maven {
        name = 'Sponge / Mixin'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
    maven {
        name = "JitPack"
        url = 'https://jitpack.io'
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup("dev.latvian.mods")
            includeGroup("dev.ftb.mods")
        }
    }
    maven { url "https://maven.shedaniel.me" }
    maven { url = 'https://maven.ladysnake.org/releases' }

    mavenCentral()
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    
    // Origins
    modCompileOnly("io.github.apace100:calio-1.11.2+mc.1.20.x") {transitive false}
    modCompileOnly("io.github.apace100:apoli-2.9.2+mc.1.20.x") {transitive false}
    modCompileOnly("io.github.apace100:Origins-1.10.2+mc.1.20.x") {transitive false}

    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}") {exclude(group: "net.fabricmc.fabric-api") transitive false}
    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}") {exclude(group: "net.fabricmc.fabric-api") transitive false}

    modCompileOnly("dev.ftb.mods:ftb-teams:${project.ftb_teams_version}")

    modCompileOnly("maven.modrinth:icarus:${project.icarus_version}+Fabric")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.4'

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}
configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}